# Generated by Django 5.1.4 on 2025-09-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateField(auto_now_add=True, verbose_name="入职时间"),
        ),
    ]
